# Generated by Django 3.0.6 on 2020-06-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustom',
            old_name='curp',
            new_name='clave_ciudadano',
        ),
    ]
